Update Obfuscatee.yml

diff --git a/.github/workflows/Obfuscatee.yml b/.github/workflows/Obfuscatee.yml
--- a/.github/workflows/Obfuscatee.yml
+++ b/.github/workflows/Obfuscatee.yml
@@ -4,9 +4,6 @@ on:
   push:
     branches:
       - main
-  schedule:
-        # Runs everyday at 1:00 AM
-        - cron: "0 1 * * *"
 
 permissions:
   contents: write
@@ -14,6 +11,7 @@ permissions:
 jobs:
   build:
     runs-on: ubuntu-latest
+    timeout-minutes: 30
 
     steps:
       - name: Check out the code
@@ -24,28 +22,48 @@ jobs:
         with:
           node-version: "latest"
 
+      - name: Cache Node.js modules
+        uses: actions/cache@v3
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
       - name: Install dependencies
         run: |
           npm install -g javascript-obfuscator
+
+      - name: Debug environment
+        run: |
+          echo "PATH: $PATH"
+          node -v
+          npm -v
+          which javascript-obfuscator
 
       - name: Clone BPB workjs
         run: |
           wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/refs/heads/main/build/unobfuscated-worker.js
 
+      - name: Check javascript-obfuscator installation
+        run: |
+          if! command -v javascript-obfuscator &> /dev/null
+          then
+              echo "javascript-obfuscator could not be found"
+              exit 1
+          fi
+
       - name: Obfuscate BPB worker js
         run: |
-          javascript-obfuscator origin.js --output _worker.js \
+          npx javascript-obfuscator origin.js --output _worker.js \
           --compact true \
           --control-flow-flattening true \
-          --control-flow-flattening-threshold 1 \
+          --control-flow-flattening-threshold 0.75 \
           --dead-code-injection true \
-          --dead-code-injection-threshold 1 \
-          --identifier-names-generator hexadecimal \
-          --rename-globals true \
+          --dead-code-injection-threshold 0.5 \
+          --identifier-names-generator mangled \
           --string-array true \
-          --string-array-encoding 'rc4' \
-          --string-array-threshold 1 \
-          --transform-object-keys true \
+          --string-array-threshold 0.75 \
           --unicode-escape-sequence true
 
       - name: Commit changes
